apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: learnflow
  namespace: argocd
spec:
  description: LearnFlow AI Tutoring Platform
  sourceRepos:
    - "https://github.com/learnflow/learnflow-app"
  destinations:
    - server: https://kubernetes.default.svc
      namespace: learnflow-staging
    - server: https://kubernetes.default.svc
      namespace: learnflow-production
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
